---
sign_in:登录
sign_up:注册
agent_panel:代理面板
admin_panel:管理面板
DBC_ADVANCED_SEARCH:高级搜索
DBC_HOME:首页
DBC_ABOUT:关于
DBC_CONTACT:联系
country:国家
state_province:州/省
city:城市
register:注册
details:详细信息
view_all:查看全部
order_by:排序
none:没有
terms_and_conditions:条款及条件
reg_success_message:帐户注册完成。一封电子邮件已发送到您的电子邮箱。请按照该电子邮件激活您的账号，谢谢。
limit:限制
usage:用途
recover:恢复
oops:哎呀，找不到网页
share_this:分享
location_map:位置图
image_gallery:图片库
gallery:图库
summary:总结
overview:概述
address:地址
message:讯息
email_subject:邮件标题
all:所有
DBC_DELETED:删除
contact_us:联系我们
DBC_ACTIVE:活跃
featured_video:精选视频
estates:专题
embed_video_url:嵌入式视频网址
DBC_PENDING:待定
email_tracker:电子邮件追踪
bulk_email:大量电子邮件
advanced_filters:高级筛选
result:结果
payment_notification:你将要做出付款。一封电子邮件将发送到您的电子邮箱。您可以从邮件中提供的链接回到这一步。
confirmation:确认
tags:标签
zip_code:邮政编号
embed_preview:嵌入预览
login:登录
post_not_found:文件未找到
view_more:查看更多
choose_a_package:选择配套
choose_feature_package:选择一个功能配套
no_package_found:没有找到配套
days:天
posts:帖子
change:修改
subscribe:订阅
image:图片
view_on_map:在地图中查看
create:创建
basic_info:基本信息
send:发送
all_email_to_users:所有寄给用户的电子邮件
email_detail:电子邮件内容
change_package:更改配套
bank_transfer:银行转帐
contact_subject:联系人邮件提要
payment_finish_title:付款完成
payment_renew_title:付款完成
payment_finish_text:您的付款已完成。当我们收到Paypal付款确认，您的帐户将被激活
payment_renew_text:您的付款已完成。当我们收到Paypal付款确认，您的帐户将被更新
payment_cancel_title:付款取消
payment_cancel_text:您的付款已被取消
feature_payment_finish:您的付款已完成。当我们收到付款确认，，您的专题将置顶。
feature_payment_cancel:您的付款被取消。
private_owner:私营业主
selected_package:所选配套
signup_with_social_account:注册社交帐户
password:密码
confirm_password:确认密码
all_posts:所有帖子
no_posts:没有帖子
title:标题
description:产品介绍
status:状态
actions:动作
action:动作
type:类型
type_something:键入文字
content:内容
featured_image:置顶图片
category:类别
all_categories:所有分类
edit_category:编辑分类
new_category:新类别
parent:家长
edit:编辑
delete:删除
name:名称
save:保存
no_parent:没有上层
edit_email_template:编辑电子邮件模板
select_template_file:选择模板文件
subject:标题
body:内容
available_variables:可用变量
select_language:选择语言
select_language_file:选择语言文件
edit_as_new:编辑成新文件
language:语言
add_another:添加另一个
export_to_file:导出到文件
import_from_file:从文件导入
auto_translator:自动翻译
from_lang:从语言
target_lang_full_name:目标语言全名
target_lang_short_name:目标语言短名
create_new_package:创建新配套
price:价格
maximum_post_by_user:用户可发最多帖子数
expirtion_time:失效时间（天数）
create_package:创建配套
edit_package:编辑配套
update_package:更新配套
add_packages:添加配套
all_packages:所有配套
no_packages:没有配套
options:选项
all_pages:所有页面
no_pages:没有页面
manage_menu:管理菜单
menu_title:菜单标题
menu_alias:菜单别名
show_in_menu:显示菜单
page_layout:页面布局
content_from:内容来自
url:网址
seo_options:搜索引擎优化选项
meta_description:Meta描述
key_words:关键词
crawl_after:再抓取（天数）
all_plugins:所有的插件
no_plugins:无插件
name_and_version:产品名称和版本
change_password:更改密码
current_password:当前密码
new_password:新密码
retype_password:再次输入密码
password_reset_info_msg:请首先设置新密码
profile_picture:头像
username:用​​户名
email:电子邮件
first_name:名
last_name:姓
gender:性别
phone:电话
company_name:公司名称
about_me:关于我
facebook_account:Facebook帐户
twitter_account:Twitter帐户
linkedin_account:LinkedIn帐户
gp_account:Google+帐户
account_msg:请输入链接，不含http：//
web_email_settings:网页电子邮址设置
contact_email:联系人电子邮址
webadmin_name:网站管理员名称
webadmin_email:网站管理员电子邮址
update:更新
upload:上传
site_settings:站点设置
site_title:网站标题
footer_text:页脚文本
site_logo:网站徽标
site_language:网站语言
site_text_direction:网站文字方向
per_page:分页每页
default_page_layout:默认页面布局
tracking_code:跟踪代码
smtp_email_settings:SMTP电子邮件设置
smtp_email:SMTP电子邮址
smtp_host:SMTP主机
smtp_port:SMTP端口
smtp_timeout:SMTP超时
smtp_user:SMTP用户
smtp_password:SMTP密码
generate_site_map:生成站点地图
sitemap_info_msg:NB请选择您需要包含在XML网站地图中的内容。完成后sitemap.xml是在root目录下保存。您还可以编辑该文件以包含你自己的网址。
pages:文章
blog_posts:博客文章
articles:文章
blog_post:博客文章
blog:博客文章
article:文章
news:新闻
view_xml:查看XML
create_xml:创建XML
manage_backups:管理备份
create_sql_backup:创建SQL备份
create_image_backup:创建映像备份
restore:恢复
download:下载
dashboard:仪表板
overview_stats_more:概述，统计和更多
visit_site:访问网站
logout:登出
themes:主题
locations:地理位置
paypal_settings:Paypal设置
payment_history:付款历史
profile:简介
packages:配套
widgets:小部件
all_widgets:所有小部件
widget_positions:小部件位置
blog_news_article:博客/新闻/文章
new_post:新文件
pages_and_menu:页和菜单
new_page:新页
menu:菜单
system:系统
manage_languages:管理语言
auto_translate:自动翻译
edit_email_text:编辑电子邮件文本
admin_settings:网站管理设置
sitemap:网站地图
activate:激活
active_theme:活跃主题
available_themes:可用主题
all_users:所有用户
create_user:创建用户
export_user_email:导出用户电子邮址（.csv格式）
profile_info:资料信息
ban_forever:永久禁止
edit_page:编辑页面
create_widget:创建小部件
widget_name:小部件名称
activate_deactivate:激活/取消激活
show:显示
available_widgets:可用的小部件
active_widgets:活跃部件
delete_warning:您确定要删除？
yes:是的”
no:不”
product_name:产品名称
fa_icon:FA图标
post_ad:提交业务清单
post_ad_subtitle:业务副标题
signin:登入
signup:注册
signup_title:创建您的帐户
not_found:未找到
purpose:用途
purpose_buy:购买
purpose_sell:销售
select_category:选择类别
contact_for_price:价格联系人
address_info:地址信息
general_info:一般信息
upload_later_msg:您可以在创建后再上传相册和视频网址
user_panel:用户面板
put_as_comma_seperated:将使用（，）逗号分割
added:添加
location:地理位置
views:查看
package_type:配套类型
post_package:基本配套
featured_package:置顶配套
both_package:基本和置顶双选
select_package:选择配套
package_created:创建配套
package_updated:更新配套
slider:滑块
add_new:新增
new_slide:新建幻灯片
update_slide:更新的幻灯片
save_order:保存订单
slider_sort_instruction:你可以拖放表行来进行排序。排序完成后记得保存。
search:搜索
results:结果
property_location_on_map:物业位置地图
location_on_map:在地图上的位置
contact_mode:联系方式
reset:重置
contact:联系人
default_site_view:默认现场查看
type_your_message:在这里键入您的信息..
mail_sent:发送邮件
search_classifieds:搜索信息
advanced_search:高级搜索
narrow_down_your_businesses:精确您的企业
home:主页
print:打印
remember_me:记住我
forgot_password:忘记密码
login_failed:登录失败
login_to_your_account:登录您的账户
register_your_account:注册您的帐户
male:男
female:女
no_location_found:未找到位置
state:州
ad_creation_error:广告制作错误！请检查。
users:用户
show_admin_user:显示管理员用户
send_email_to_business:发送电子邮件至业务
DBC_PAYMENT_PENDING:付款待处理
DBC_EXPIRED:过期
categories:分类
top_posts:置顶帖子
show_state_province:显示州省
package_settings:配套设置
default_site_settings:默认站点设置
webadmin_settings:网站管理设置
banner_settings:横幅设置
max_price_for_search:最高搜索价格
search_filters:搜索过滤
posts_per_page:每页帖子数
recent_posts:最近的帖子
featured_posts:精选文章
top_locations:热门地区
top_users:用户排行
approve:批准
make_featured:请置顶
remove_featured:移除置顶
renew_featured:更新置顶
renew_package:更新配套
no_renew_post_id:无效的更新ID
approve_payment:付款批准
transaction:交易
transaction_id:交易ID
post_id:文章ID
amount:金额
request_date:申请日期
expiration_date:失效日期
transaction_deleted:交易删除
payment_approved:付款批准
logged_in_as:登入身分
posted_on:发布于
confirm_email_send:电子邮件已寄出.请遵循电子邮件的指示。
email_confirmed:电子邮件确认.您现在可以使用您的电子邮址和密码登录
email_confirmed_failed:确认失败.确认电子邮址和密码不匹配。
password_change_success:密码修改成功
email_sent_inbox:电子邮件发送到您的收件箱.请查收该电子邮件。
password_recovery_link_invalid:密码恢复链接无效
user_updated:用户更新
user_deleted:用户删除
user_banned:用户被禁止
user_unbanned:用户已解除封锁
user_confirmed:用户确认
post_deleted:帖子已删除
post_updated:帖子更新
post_created:帖子创建
post_featured:帖子置顶
data_inserted:数据插入
data_updated:数据更新
feature_renewed:置顶续订
post_feature_removed:帖子删除置顶
post_approved:帖子批准
invalid_post:无效的帖子
email_sent:电子邮件发送
settings_updated:设置更新
package_removed:配套移除
page_updated:页更新
page_created:页创建
page_deleted:页删除
menu_updated:菜单更新
site_map_generation_success:XML网络地图成功建立。
select_option:请选择一个或以上的选项。
image_backup_created:映像备份创建成功
language_translated:语言翻译
unable_to_write_file:无法写入文件
backup_deleted:备份删除
database_restored:数据库恢复
theme_activated:主题激活
user_created:用户创建成功
widget_position_updated:部件当前位置更新成功
widget_created:部件创建成功
widget_data_updated:小部件的数据更新成功
unable_to_write_widget:无法写入小部件
post_created_and_published:帖子创建和发布成功
post_created_approval:帖子创建成功，等待管理员批准
post_package_renewed:基本配套更新成功
payment_finish:付款完成
payment_cancelled:付款已取消
admin_change_pass_help:如果没有更改请留空
go_to_paypal:进入Paypal
login_with_google:登录谷歌
login_with_facebook:使用Facebook登入
load_more_recent_posts:加载更多最近的帖子
load_more_featured_posts:加载更多置顶帖子
register_for_new_account:注册新帐号
site_map:站点地图
show_site_map:显示站点地图
service:服务
features:置顶
about:关于
view_posts:查看帖子
see_full_documentation:查看完整的帮助文档
select_city:选择城市
parallax_slider:视差滑块
all_slides:所有幻灯片
no_slide:没有幻灯片
slide_order:滑动秩序
edit_profile:修改个人资料
post_price_settings:帖子价格设定
enable_post_pricing:启用帖子定价
enable_paypal_transfer:启用Paypal转账
enable_bank_transfer:启用银行转账
bank_transfer_instruction_for_posts:银行转帐指令
featured_price_settings:置顶价格设定
enable_featured_pricing:启用置顶的定价
enable_featured_paypal:启用置顶Paypal
enable_featured_bank_transfer:启用置顶银行转账
bank_transfer_instruction_for_featured_posts:置顶银行转账指令
bank_currency_settings:银行货币设置
bank_currency:银行货币
use_same_as_paypal_currency:使用与Paypal相同的货币
admin:管理员
re_password:再次输入密码
explain_widget_position:解释部件位置
post:帖子
post_renew:帖子更新
feature:置顶
feature_renew:置顶更新
payment_for:支付项目
select_country:选择国家
select_one:请选择一个
video_url:视频网址
confirm_payment:确认付款
package_title:配套标题
number_of_featured_days:置顶的天数
no_of_days:天数
expiration_time:失效时间
any_city:任何城市
any_category:任何类别
product_admin_panel:产品管理员面板
username_or_email:用户名或电子邮址
business_detail:业务细节
post_detail_subtitle:帖子副标题
posts_by:帖子排序
featured:置顶
edit_user:编辑用户
the_field_is_required:％s文本框中是必需的。
valid_email:％s文本框中必须包含一个有效的电子邮件地址。
min_length:％s文本框中必须有至少％s的长度字符。
numeric:％s文本框中只能包含数字。
matches:％s文本框中的文字不能和％s的字段相匹配。
greater_than:％s文本框中必须包含一个大于％s的数字。
agree_terms:我已读过％s的条款及条件％s
must_accept_terms:你必须接受条款和条件
dont_have_permission:您没有权限访问此页面
email_allready_in_use:电子邮址已存在
username_allready_in_use:用户名已存在
current_password_not_matched:当前密码不匹配
email_or_password_not_mathed:邮箱或密码不匹配
email_not_matched:邮址不匹配
account_not_confirmed:帐户还未证实
all_locations:所有位置
add_country:添加国家
add_state:添加州
add_city:添加城市
no_locations:没有位置
banner_type:横幅类型
bg_image:背景图像
unique_alias:％s文本框中需要是唯一的
error_occured:发生错误。请检查下面的字段
user_profile:用户配置文件“
user_email:用户邮址
target_lang_name:目标语言名称
no_emails:无电子邮件
to:到
classified_settings:分类设置
publish_posts_directly:直接发布帖子
system_currency:系统货币
enable_signup:启用注册
if_package_expired:如果配套过期
do_not_hide:不要隐藏
hide:隐藏
show_price_like:价格格式
facebook_app_settings:Facebook应用程序设置
enable_facebook_login:启用Facebook登录
fb_app_id:Facebook应用程序ID
fb_secret_key:Facebook的密钥
comment_settings:评论设置
enable_comment:启用评论
disqus_shortname:Disqus 短名
sandbox_mode:沙盒模式
item_name:项目名称
paypal_email:Paypal电子邮址
currency:货币
finish_url:完成网址
cancel_url:取消网址
menu_background:菜单背景
menu_text_color:菜单文本颜色
activated_menu_color:激活菜单颜色
top_bar_bg:顶栏背景颜色
activated_menu_text_color:激活菜单文本颜色
latitude:纬度
longitude:经度
map_zoom:地图​​缩放
search_panel_settings:搜索面板设置
search_panel_bg_color:搜索面板背景色
show_background_image:显示背景图片
active_widget_position:活跃部件位置
upload_and_install:上传和安装
install_updates:安装更新/主题/插件/小部件
confirmation_email:确认电子邮址
recovery_email:恢复电子邮址
signup_notification_email:注册电子邮件通知
payment_confirmation_email:付款确认电子邮件
click_and_edit:选择一个模板文件，然后单击编辑]
google_analytics_settings:谷歌Analytics设置
default_seo_settings:默认SEO设置
individual:个人
find_us_on_facebook:在Facebook上找到我们
category_featured_posts:分类置顶帖子
load_more_posts:加载更多
home_page_title:搜索和发表顶级广告
no_posts_found:无帖子
type_anything:输入任何东西
chosen_not_found:哎呀，没有找到！
rating_asc:评分升序
rating_desc:评分降序
id_desc:ID降序
id_asc:ID升序
show_daily_menu:显示每日菜单
website:网站
founded:成立于
year:年
price_range:价格范围
additional_features:附加功能
add_more_fields:添加更多输入框
remove:删除
distance_around_my_position:距离我现在位置
show_distance_in:显示距离
business_listed:发布企业
show_street_view:显示街景
list_business:列表业务
search_businesses:搜索业务
top_businesses:最热的企业
featured_businesses:置顶业务
business_directory_settings:商业指南设置
hide_email:隐藏电子邮件
hide_phone:隐藏电话
review:述評
comment:评论
submit_review:提交述評
rating:评分
review_alert:您必须登录才能提交述評。
new_business:新业务
identify_my_location:确定我的位置
data_deleted:数据删除
recent_reviews:近期评论
view_all_reviews:查看所有述評
review_deleted:删除述評
review_detail:述評详细
all_reviews:所有述評
monday:周一
tuesday:周二
wednesday:周三
thursday:周四
friday:周五
saturday:周六
sunday:周日
opening_hour:开放时间
closed:关闭
airport:机场
cafe:咖啡厅
cinemas:电影院
hotels_and_resorts:酒店及度假村
libraries:图书馆
night_clubs:酒吧和夜总会
offices:办公室
restaurants:餐厅
shops:商店
review_submitted:提交述評
social_links:社交链接
upgrade_browser:升级浏览器
please_upgrade_your_browser:请升级您的浏览器
business:商务
introduction:简介
terms:条款和条件
email_not_found:邮址未找到
city_dropdown:城市下拉
published:发表
publish:发布
drafted:起草
draft:草案
from:从
send_bulk_email:发送大量电子邮件
ive_read_the:我读过
title_city_category:标题，城市或类别
dt_first:首页
dt_last:末页
dt_next:下一页
dt_prev:上一页
dt_no_data:列表中没有数据
dt_show_empty:显示0至0共0项
dt_no_match:未找到匹配的记录
dt_search:搜索
dt_processing:处理中...
dt_loading:载入中...
dt_info:显示_START_ 到 _END_ 的 _TOTAL_ 条目
dt_filter_info:（从_MAX_总条目过滤）
dt_show_entries:显示_MENU_项
get_directions:获取方向指示
review_not_submitted :你已经提供了评述
debug_email :调试邮件
email_to :电邮
report_the_business :报告此业务
reported :报告
already_reported :已报告
reported_post :报告的帖子
all_reported_posts :所有报告的帖子
report:报告
assigned_to:分配给
select_assigned_to:选择用户
css_compression:CSS压缩
gallery_notes:您可以拖放重新排列相册。照片不调整大小。
video_notes:YouTube或Vimeo的网址
post_expiration_notification:帖子到期通知
claim_the_business:商家宣称主权
claim_business_instructions:填写以下表格，单击发送按钮。网站管理员将通过电子邮件或电话与您联系。
claimed_business:宣称业务
days_left:剩余天数
AM:上午
PM:下午
upload_invalid_min_dimensions:上传的图像尺寸太低
view_on_front:在前页查看
clear_unused_img:清除未使用的图像
unused_files_found:发现未使用的文件
clear_unused_img:清除未使用的图像
unused_images_cleared:未使用图像清除
unused_info_msg:此函数只清除其中​​不被使用（用户，类别，网页，博客）的图像。它通过搜索数据库寻找图像.如果你手动上传任何图像，并在代码中使用它们，它可能会被删除。
no_unused_img:没有发现未使用的图像
search_panel_filter_type:过滤器类型
basic_options:基本选项
advanced_options:高级选项
key_words:关键词
sorting_order:排序顺序
business_listed_on:企业列出于
business_listed_under:商务列出在
all_sub_categories:所有子类
no_sub_categories:无子类
open_24_by_7:始终打开
hide_my_email :隐藏我的电子邮址
disable_email_contact:禁用电子邮件联系
enable_review:启用评述
disable_google_street_view:禁用谷歌街景
location_chorome_msg:由于谷歌位置服务不可用（仅适用于Chrome浏览器）于非SSL站点。你想使用你的IP地址来查询位置？ 注-结果可能与谷歌有所差异
send_email_to_users:向用户发送电子邮件
show_banner:显示横幅
hide_my_phone:隐藏我的电话号码
kms:里
miles:万里
logo_text:标志文本
logo_type:标志类型
logo_text_color:标志文本颜色
Jan:一月
Feb:二月
Mar:三月
Apr:四月
May:可能
Jun:君
Jul:七月
Aug:八月
Sep:九月
Oct:Oct
Nov:十一月
Dec:月
show_search_panel:显示搜索面板
delete_selected:删除所选
camera_spin:相机旋转
degree:学历
map_api_key:GMAP API密钥
pricing:定价
post_package_instruction:我们在下面的包在我们的网站张贴的业务
feature_package_instruction:我们已经为特色制订经营下列包
MENU:MENU
gplus_app_settings:Google+应用设置
auth_redirect_url:授权重定向URL
enable_gplus_login:启用Google+登录
gplus_client_id:Google+的客户端ID
gplus_client_secret:Google+的客户端密钥
how_to_get_gplus_api:如何获取Google+客户端ID和秘密
gallery_upload_limit:画廊上传限制
you_can_upload_max:您可以上传最多
gallery_photos:相册